Models/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CMS_Umbraco_Inlämning.Models
{
    public class ContactFormViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CMS_Umbraco_Inlämning.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

Controllers/ContactController.cs
using CMS_Umbraco_Inlämning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace CMS_Umbraco_Inlämning.Controllers
{
    public class ContactController : SurfaceController
    {
        public ActionResult RenderContactForm()
        {
            return PartialView("_ContactForm", new ContactFormViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleContactForm(ContactFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            MailMessage email = new MailMessage("noreply@local.com", model.Email)
            {
                Subject = "Contact Request",
                Body = model.Message
            };

            try
            {
                SmtpClient smtp = new SmtpClient();
                smtp.Send(email);
            }
            catch (Exception ex)
            {

                throw ex;
            }

            TempData["IsSuccesful"] = true;

            return CurrentUmbracoPage();
        }
    }
}

Controllers/MemberController.cs
using CMS_Umbraco_Inlämning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;

namespace CMS_Umbraco_Inlämning.Controllers
{
    public class MemberController : SurfaceController
    {
        // GET: Member
        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult SubmitLogin(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError("", "The username or password provided is incorrect");
                }
            }
            return CurrentUmbracoPage();
        }
        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }
    }
}

Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
	var searchQuery = Request.QueryString["query"];
}



<!-- Banner -->
<section id="banner">
	<h2>@Model.Value("pageTitle")</h2>
	<p>@Model.Value("bodyText")</p>
</section>

<!-- One -->
<section id="one" class="wrapper style1">
	<div class="inner">
		<article class="feature left">
			<div class="content">
                <form method="GET" id="search">
                    <div class="row">
                        <div>
                            <input type="text" class="form-control" placeholder="Search.." name="query" value="@searchQuery" />
						</div>
                        <div>
                            <button class="btn btn-primary">Search <i class="fa fa-search"></i></button>
						</div>
                        <div>
							@if (!string.IsNullOrEmpty(searchQuery))
                            {
								var results = Umbraco.ContentQuery.Search(searchQuery);
								int resultsCount = results != null && results.Any() ? results.Count() : 0;
								<div>
                                    <p>We found <strong>@resultsCount</strong> result@(resultsCount != 1 ? "s" : "") when we searched for <strong>@searchQuery</strong></p>
									@if(resultsCount > 0)
                                    {
										<ul>
											@foreach(var result in results)
                                            {
												<li>
													<h3><a href="@result.Content.Url()">@result.Content.Name</a></h3>
													
												</li>
                                            }
										</ul>
                                    }
								</div>
                            }
						</div>
					</div>
				</form>
			</div>
		</article>
	</div>
</section>



<section id="one" class="wrapper style1">
	<div class="container 75%">
		<div class="row 200%">
			<div class="6u 12u$(medium)">
				<header class="major">
					<h2>Maecenas luctus lectus</h2>
					<p>Perspiciatis doloremque recusandae dolor</p>
				</header>
			</div>
			<div class="6u$ 12u$(medium)">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non ea mollitia corporis id, distinctio sunt veritatis officiis dolore reprehenderit deleniti voluptatibus harum magna, doloremque alias quisquam minus, eaque. Feugiat quod, nesciunt! Iste quos ipsam, iusto sit esse.</p>
				<p>Dolorum aspernatur maxime libero ratione quidem distinctio, placeat fugiat laborum voluptatum enim neque soluta vel sunt id ex veritatis. Labore rerum, odit sapiente, alias mollitia magnam exercitationem modi amet earum quia atque ipsum voluptas asperiores quas laboriosam.</p>
			</div>
		</div>
	</div>
</section>

<!-- Two -->
<section id="two" class="wrapper style2 special">
	<div class="container">
		<header class="major">
			<h2>Fusce ultrices fringilla</h2>
			<p>Maecenas vitae tellus feugiat eleifend</p>
		</header>
		<div class="row 150%">
			<div class="6u 12u$(xsmall)">
				<div class="image fit captioned">
					<img src="images/pic02.jpg" alt="" />
					<h3>Lorem ipsum dolor sit amet.</h3>
				</div>
			</div>
			<div class="6u$ 12u$(xsmall)">
				<div class="image fit captioned">
					<img src="images/pic03.jpg" alt="" />
					<h3>Illum, maiores tempora cupid?</h3>
				</div>
			</div>
		</div>
		<ul class="actions">
			<li><a href="#" class="button special big">Nulla luctus</a></li>
			<li><a href="#" class="button big">Sed vulputate</a></li>
		</ul>
	</div>
</section>

<!-- Three -->
<section id="three" class="wrapper style1">
	<div class="container">
		<header class="major special">
			<h2>Mauris vulputate dolor</h2>
			<p>Feugiat sed lorem ipsum magna</p>
		</header>
		<div class="feature-grid">
			<div class="feature">
				<div class="image rounded"><img src="images/pic04.jpg" alt="" /></div>
				<div class="content">
					<header>
						<h4>Lorem ipsum</h4>
						<p>Lorem ipsum dolor sit</p>
					</header>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore esse tenetur accusantium porro omnis, unde mollitia totam sit nesciunt consectetur.</p>
				</div>
			</div>
			<div class="feature">
				<div class="image rounded"><img src="images/pic05.jpg" alt="" /></div>
				<div class="content">
					<header>
						<h4>Recusandae nemo</h4>
						<p>Ratione maiores a, commodi</p>
					</header>
					<p>Animi mollitia optio culpa expedita. Dolorem alias minima culpa repellat. Dolores, fuga maiores ut obcaecati blanditiis, at aperiam doloremque.</p>
				</div>
			</div>
			<div class="feature">
				<div class="image rounded"><img src="images/pic06.jpg" alt="" /></div>
				<div class="content">
					<header>
						<h4>Laudantium fugit</h4>
						<p>Possimus ex reprehenderit eaque</p>
					</header>
					<p>Maiores iusto inventore fugit architecto est iste expedita commodi sed, quasi feugiat nam neque mollitia vitae omnis, ea natus facere.</p>
				</div>
			</div>
			<div class="feature">
				<div class="image rounded"><img src="images/pic07.jpg" alt="" /></div>
				<div class="content">
					<header>
						<h4>Porro aliquam</h4>
						<p>Quaerat, excepturi eveniet laboriosam</p>
					</header>
					<p>Vitae earum unde, autem labore voluptas ex, iste dolorum inventore natus consequatur iure similique obcaecati aut corporis hic in! Porro sed.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Four -->
<section id="four" class="wrapper style3 special">
	<div class="container">
		<header class="major">
			<h2>Aenean elementum ligula</h2>
			<p>Feugiat sed lorem ipsum magna</p>
		</header>
		<ul class="actions">
			<li><a href="#" class="button special big">Get in touch</a></li>
		</ul>
	</div>
</section>

Views/KontaktaOss.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.KontaktaOss>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

<section id="four" class="wrapper style3 special">
	<div class="container">
		<header class="major">
			<h2>@Model.Value("title")</h2>
			<p>@Model.Value("bodyText")</p>
		</header>
		
	</div>
</section>
<div>
    @{
        Html.RenderAction("RenderContactForm", "Contact");
    }
</div>

Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

	<section id="main" class="wrapper">
		<div class="container">
			<header class="major special">
				<h2>@Model.Value("pageTitle")</h2>

			</header>
			<div>
				@{
					Html.RenderAction("RenderLogin", "Member");
				}
			</div>
		</div>
	</section>

Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}
@{
    var site = Model.Root();
    var selection = site.Children.Where(x => x.IsVisible()); <!-- see below for explanation of IsVisible helper method -->
}

<!DOCTYPE HTML>
<!--
	Spatial by TEMPLATED
	templated.co templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Spatial by TEMPLATED</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="/assets/css/main.css" />
	</head>
	<body class="landing">

		<!-- Header -->
		@if (Umbraco.MemberIsLoggedOn())
		{
			<header id="header" class="alt">
				<h1><strong><a style="color:goldenrod" class="nav-link @Html.Raw(Model.Id == site.Id ? " navi-link--active" : "" )" href="@site.Url">@site.Name</a></strong></h1>

				<!-- Nav -->
				<nav id="nav">
					<ul>
						@foreach (var item in selection)
						{
							<li class="nav-item">
								<a class="nav-link @(item.IsAncestorOrSelf(Model) ? " nav-link--active" : null)" href="@item.Url">@item.Name</a>
							</li>
						}
					</ul>
					@using (Html.BeginUmbracoForm("SubmitLogout", "Member", FormMethod.Post, new { id = "logout" }))
					{
						var myUser = Membership.GetUser();
						if (myUser != null)
						{
							@:<div>
								@:<p><strong>Logged in as </strong><span>@myUser.UserName </span><span><button name="logout" type="submit"><span>logout</span><i class="fa fa-arrow-right"></i></button></span></p>
								@*@:<button name="logout" type="submit"><span>logout</span><i class="fa fa-arrow-right"></i></button>*@
							@:</div>
						}
					}


					@*<ul>
						<li><a href="/kontakta-oss">Generic</a></li>
						<li><a href="elements.html">Elements</a></li>
					</ul>*@
				</nav>

				@*<nav id="nav">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li><a href="generic.html">Generic</a></li>
						<li><a href="elements.html">Elements</a></li>
					</ul>
				</nav>*@
			</header>

			<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>
		}
		else
		{
			<header id="header" class="alt">
				<h1><strong><a class="nav-link @Html.Raw(Model.Id == site.Id ? " navi-link--active" : "" )" href="@site.Url">@site.Name</a></strong></h1>

				<!-- Nav -->
				<nav id="nav">
					<ul>
						<li>
							<a class="nav-link @Html.Raw(Model.Id == site.Id ? " navi-link--active" : "" )" href="/register">Register</a>
							<a class="nav-link @Html.Raw(Model.Id == site.Id ? " navi-link--active" : "" )" href="/login">Login</a>
						</li>
					</ul>

				</nav>
				
			</header>

			<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>
		}



		@RenderBody()

		<!-- Footer -->
		<footer id="footer">
			<div class="container">
				<ul class="icons">
					<li><a href="#" class="icon fa-facebook"></a></li>
					<li><a href="#" class="icon fa-twitter"></a></li>
					<li><a href="#" class="icon fa-instagram"></a></li>
				</ul>
				<ul class="copyright">
					<li>&copy; @Model.Value("footerText", fallback: Fallback.ToAncestors)</li>
					<li>Design: <a href="http://templated.co">TEMPLATED</a></li>
					<li>Images: <a href="http://unsplash.com">Unsplash</a></li>
				</ul>
			</div>
		</footer>

		<!-- Scripts -->
		<script src="assets/js/jquery.min.js"></script>
		<script src="assets/js/skel.min.js"></script>
		<script src="assets/js/util.js"></script>
		<script src="assets/js/main.js"></script>

	</body>
</html>

Views/MembersOnlyError.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.MembersOnlyError>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

<section id="main" class="wrapper">
	<div class="container">
		<header class="major special">
			<h2>@Model.Value("pageTitle")</h2>
			<p>@Model.Value("bodyText")</p>
		</header>
		<div style="margin:auto;width:60%;padding:10px;>
		    <a href="/register">Register</a>
		    <a href="/login">Login</a>
            
        </div>
	</div>
</section>

Views/Partials/BlockList/Default.cshtml
@inherits UmbracoViewPage<BlockListModel>
@using Umbraco.Core.Models.Blocks
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;
        @Html.Partial("BlockList/Components/" + data.ContentType.Alias, block)        
    }
</div>

Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@*
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row)
                    }
                </div>
            }
        }else {
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row)
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true)
                    }
                </div>
            }
        }else {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false)
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @if (singleColumn) {
            @:<div class="container">
        }
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @if (singleColumn) {
            @:</div>
        }
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@{
    string embedValue = Convert.ToString(Model.value);
    embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;
}

<div class="video-wrapper">
	@Html.Raw(embedValue)
</div>

Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Core.PropertyEditors.ValueConverters

@if (Model.value != null)
{
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var value = TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider);
    value = TemplateUtilities.ResolveUrlsFromTextString(value);
    value = TemplateUtilities.ResolveMediaFromTextString(value);
}
@Html.Raw(value)

Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode((string)Model.value.ToString())).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Views/Partials/_ContactForm.cshtml
@model CMS_Umbraco_Inlämning.Models.ContactFormViewModel

@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}

@if (Convert.ToBoolean(TempData["IsSuccesful"]))
{
    <h1>Succes!</h1>
    <p>Thanks for sending your message</p>
}
else
{
    using (Html.BeginUmbracoForm("HandleContactForm", "Contact"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        <div style="margin:auto;width:60%;padding:10px">
            <div>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { placeholder = "Enter your name..." })
            </div>
            <br />
            <div>
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email, new { placeholder = "Enter your email..." })
            </div>
            <br />
            <div>
                @Html.LabelFor(m => m.Message)
                @Html.TextAreaFor(m => m.Message, new { placeholder = "Enter your message..." })
            </div>
            <br />
            <input type="submit" name="submit" value="Send" />
        </div>
    }
}

Views/Partials/_Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<CMS_Umbraco_Inlämning.Models.LoginViewModel>
@using Umbraco.Web

@if (!Umbraco.MemberIsLoggedOn())
{
    using (Html.BeginUmbracoForm("SubmitLogin", "Member", System.Web.Mvc.FormMethod.Post, new { id = "login" }))
    {
        @Html.AntiForgeryToken()

        <div style="margin:auto;width:30%;padding:10px;">

            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { placeholder = "Username" })
            <br />

            @Html.LabelFor(m => m.Password)
            @Html.PasswordFor(m => m.Password, new { placeholder = "Password" })
            <br />

            <button name="login" type="submit">Login</button>
        </div>
    }
}

Views/ProductItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ProductItem>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
	var image = Model.Value<IPublishedContent>("image");
}
<section id="four" class="wrapper style3 special">
	<div class="container">
		<header class="major">
			
			
		</header>
	</div>
</section>
<section id="main" class="wrapper">
    <div class="container">

        <div>
            <h2>@Model.Value("productName")</h2>
            <h4>@Model.Value("description")</h4>
            <p style="font-weight:bold">@Model.Value("price") SEK</p>
            <img style="width:50%" src="@image.Url"/>
        </div>
    </div>
</section>

Views/Products.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Products>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

@{
	var selection = Umbraco.Content(Guid.Parse("d4593191-7f6f-425b-8574-76480928968e"))
    .ChildrenOfType("productItem")
    .Where(x => x.IsVisible())
    .OrderByDescending(x => x.CreateDate);
}


<section id="four" class="wrapper style3 special">
	<div class="container">
		<header class="major">
			<h2>@Model.Value("title")</h2>
			<p>@Model.Value("bodyText")</p>
		</header>
	</div>
</section>


<section id="main" class="wrapper">
<div class="container">
 
@foreach (ContentModels.ProductItem item in selection)
{
   <a href="@item.Url">
            
            <h3>@item.ProductName</h3>
            <h4>@item.Price SEK</h4>
            <img style="width:200px" src="@item.Image.Url" alt="Alternate Text" />
            <hr>
    </a>
}

</div>
</section>

        